global:
  resolve_timeout: 1m

route:
  receiver: "jenkins-rollback-webhook"
  group_by: ["alertname", "severity"]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 24h
  routes:
    - match:
        severity: critical
      receiver: "jenkins-rollback-webhook"
      group_wait: 5s
      repeat_interval: 24h

receivers:
  - name: "jenkins-rollback-webhook"
    webhook_configs:
      - url: "http://35.153.30.23:8080/generic-webhook-trigger/invoke?token=ROLLBACK_0FAA6A_TOKEN"
        send_resolved: false
        http_config:
          basic_auth:
            username: "admin"
            password: "11fefb75479347ea2d8fde33526408be1e"

inhibit_rules: []
